"""
Action Grounding Module

SeeAct Action Grounding Module: responsible for grounding action plans generated by the action generation module into concrete UI actions.

Input:
- Textual Plan 
- loaded model (Qwen-2.4-VL-2B-Instruct), used when required for grounding
- action value (Image, Instruction, DOM value, etc.)
- annotation id (for logging/debugging purposes)
- Method number (1-3) 
1. Element Attributes 
2. Textual Choice 
3. Image Annotation
"""

from AutoWeb.src.model_interface import VLModel
from typing import Dict


class SeeActActionGrounding:
    def __init__(self, model:VLModel):
        self.model = model

    def _ground_using_element_attributes(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using element attributes
        print(f"    Grounding using Element Attributes for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using element attributes.
        pass

    def _ground_using_textual_choice(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using textual choice
        print(f"    Grounding using Textual Choice for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using textual choice.
        pass

    def _ground_using_image_annotation(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using image annotation
        print(f"    Grounding using Image Annotation for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using image annotation.
        pass

    def _invalid_method(self, annotation_id:str, textual_plan: str, step_info: Dict):
        print(f"    ✗ Invalid grounding method specified for annotation '{annotation_id}'.")
        return None

    def process(
                self, 
                method: str, 
                annotation_id:str,
                textual_plan: str,
                step_info: Dict,
                ):
        """
        Process the action grounding based on the specified method.
        
        Args:
            method: An integer (1-3) indicating the grounding method to use.
            annotation_id: Identifier for the current annotation being processed.
        
        Returns:
            Grounded action details (format may vary based on method).
        """
        print(f"  ⏳ Processing action grounding using method {method} for annotation '{annotation_id}' in dataset '{dataset_file_name}'...")
        
        switcher = {
            "1": self._ground_using_element_attributes,
            "2": self._ground_using_textual_choice,
            "3": self._ground_using_image_annotation
        }
        grounding_function = switcher.get(method, self._invalid_method)

        result = grounding_function(annotation_id, textual_plan, step_info)
        
        if result is None:
            return {
                "error": f"Invalid grounding method '{method}' specified."                
            }

        # Here we would have the actual code to perform action grounding based on the specified method.
        # For now, we will just return a placeholder string.
        return result