"""
Action Grounding Module

SeeAct Action Grounding Module: responsible for grounding action plans generated by the action generation module into concrete UI actions.

Input:
- Textual Plan 
- loaded model (Qwen-2.4-VL-2B-Instruct), used when required for grounding
- action value (Image, Instruction, DOM value, etc.)
- annotation id (for logging/debugging purposes)
- Method number (1-3) 
1. Element Attributes 
2. Textual Choice 
3. Image Annotation
"""

import time
import torch
from AutoWeb.src.config import get_deberta_model_path
from AutoWeb.src.model_interface import VLModel
from AutoWeb.src.gpt_model import GPTVisionModel
from typing import Dict, List, Union

from AutoWeb.src.utils.html_to_dom import extract_interactive_elements
from AutoWeb.src.utils.img_downscaler import downscale_image_if_needed
from AutoWeb.src.utils.load_DeBERTa import DeBERTaLoader
import re
import json
import ast


class SeeActActionGrounding:
    def __init__(
            self, 
            model: Union[VLModel, GPTVisionModel],
            method: str = "2"
            ):
        self.model = model
        self.method = method

        self.switcher = {
            "1": self._ground_using_element_attributes,
            "2": self._ground_using_textual_choice,
            "3": self._ground_using_image_annotation
        }

        self.grounding_function = self.switcher.get(self.method, self._invalid_method)

        if self.grounding_function == self._invalid_method:
            print(f"  ⚠️ Warning: Invalid grounding method '{self.method}' specified. Defaulting to invalid method handler.")
            # Block execution if the method is invalid
            raise ValueError(f"Invalid grounding method '{self.method}' specified. Please choose a valid method (1, 2, or 3).") 
        
        # Load the DeBERTa model for groudning method "2" (Textual Choice)
        self.deberta_loader = None
        self.deberta_model = None
        if self.method == "2":
            self.load_deberta()
            print(f"  ✅ DeBERTa model loaded successfully.")
        


    def load_deberta(self):        
        deberta_model_path = get_deberta_model_path()
        
        # Use pre-trained cross-encoder from sentence-transformers (recommended).
        # Falls back to legacy DeBERTa-base + random head only if explicitly disabled.
        self.deberta_loader = DeBERTaLoader(
            model_path=deberta_model_path,
            use_pretrained_crossencoder=True,           # ← pre-trained cross-encoder
            crossencoder_name="cross-encoder/ms-marco-MiniLM-L-6-v2",
        )
        self.deberta_loader.load_model()
        self.deberta_model = self.deberta_loader.model  # may be None for pre-trained path

    def _ground_using_element_attributes(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using element attributes
        print(f"    Grounding using Element Attributes for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using element attributes.
        pass

    def select_element_from_candidates(self, textual_plan: str, candidates: List[Dict], website_screenshot, user_instruction: str = ""):
        """
        Grounding Using Textual Choice - Select the best matching element from the top candidates using the Qwen model.
        """
        # Build a compact enumerated candidate list for the few-shot prompt
        enumerated_candidates = "\n".join([f"{i}. {c['element']['representation']} (score: {c['score']:.4f})" for i, c in enumerate(candidates)])

        # Few-shot prompt that forces a single-line 'Answer: <index|NO_MATCH>' output
        prompt = f"""
You are an assistant that selects the best candidate from a numbered list. Return EXACTLY ONE token only: the 0-based index of the chosen candidate, or the token NO_MATCH if none apply. Do NOT output JSON, explanation or other text.

EXAMPLES:
Candidates: 0. "Search"  1. "Sign in"  2. "Add to cart"
Plan: Click on the search box
Answer: 0

Candidates: 0. "Price"  1. "Reviews"  2. "Buy now"
Plan: Click the buy button
Answer: 2

NOW:
user instruction: {user_instruction}

Website screenshot: <|vision_start|><|image_pad|><|vision_end|>

Candidates:
{enumerated_candidates}

Plan: {textual_plan}

Answer:
"""

        # Deterministic generation: low token budget, no sampling
        def call_model(p, max_tokens=6):
            r = self.model.infer(
                image_or_tensor=downscale_image_if_needed(website_screenshot) if website_screenshot else None,
                prompt_text=p,
                max_new_tokens=max_tokens,
                do_sample=False,
                temperature=0.0
            )
            if isinstance(r, dict):
                return (r.get('output_text') or r.get('raw_text') or str(r)).strip(), r
            return str(r).strip(), r

        resp_text, raw_resp = call_model(prompt, max_tokens=6)
        print(f"    Model response for element selection (text): {resp_text}")

        # quick retry with stricter instruction if response is not a single token
        retry_prompt = prompt + "\n(Reply with a single token: an integer index or NO_MATCH)"
        retry_attempted = False
        if not re.search(r"\b(NO_MATCH|\d+)\b", resp_text, re.IGNORECASE):
            retry_attempted = True
            print("    ⚠ Initial response not parseable — retrying with stricter prompt")
            resp_text, raw_resp = call_model(retry_prompt, max_tokens=4)
            print(f"    Retry response: {resp_text}")
        
        # Diagnostics: show top candidates (reprs) to help debugging
        try:
            preview_candidates = [c["element"]["representation"] for c in candidates[:5]]
            print(f"    Candidate count={len(candidates)}, top previews={preview_candidates}")
        except Exception:
            pass

        # 1) Try plain integer extraction (single digit or multi-digit)
        m = re.search(r"\b(\d+)\b", resp_text)
        if m:
            try:
                idx = int(m.group(1))
                if 0 <= idx < len(candidates):
                    print(f"   Selected element : {candidates[idx]['element']},  (index {idx})")
                    return candidates[idx]["element"]
                else:
                    print(f"    Parsed index {idx} out of range (0..{len(candidates)-1})")
            except Exception as e:
                print(f"    Error converting parsed index: {e}")

        # 2) Try to locate JSON object after the token (e.g. Selected element: {...})
        json_obj = None
        jmatch = re.search(r"Selected element\s*[:\-\[]\s*(\{.*\})", resp_text, re.DOTALL | re.IGNORECASE)
        if jmatch:
            js = jmatch.group(1)
            try:
                json_obj = json.loads(js)
            except Exception:
                try:
                    json_obj = ast.literal_eval(js)
                except Exception:
                    json_obj = None

        # 3) If we received a JSON-like object as the whole response, try to parse it
        if not json_obj:
            try:
                if resp_text.startswith('{') and resp_text.endswith('}'):
                    json_obj = json.loads(resp_text)
            except Exception:
                try:
                    json_obj = ast.literal_eval(resp_text)
                except Exception:
                    json_obj = None

        # 4) If JSON object found, try to match its 'text' or attributes against candidates
        if isinstance(json_obj, dict):
            probe_text = json_obj.get('text') or ''
            # if probe_text is empty, try attributes -> join attribute values
            if not probe_text and isinstance(json_obj.get('attributes'), dict):
                probe_text = ' '.join(str(v) for v in json_obj['attributes'].values() if v)

            probe_text = probe_text.strip()
            if probe_text:
                # basic string-match scoring
                best_idx = None
                best_score = 0
                for i, c in enumerate(candidates):
                    repr_text = c['element'].get('representation', '') or ''
                    a = repr_text.lower()
                    b = probe_text.lower()
                    score = 0
                    if b in a or a in b:
                        score = max(score, 100)
                    # token overlap
                    toks_a = set(a.split())
                    toks_b = set(b.split())
                    ov = len(toks_a & toks_b)
                    score += ov
                    if score > best_score:
                        best_score = score
                        best_idx = i
                if best_idx is not None and best_score > 0:
                    print(f"    Matched JSON 'text' to candidate index={best_idx} (score={best_score})")
                    return candidates[best_idx]['element']
                else:
                    print("    JSON returned by model contained text but no candidate matched confidently")
            else:
                print("    JSON returned by model is empty or has no text/attributes")

        # 5) As a robust fallback, pick the top DeBERTa/scored candidate (best similarity)
        try:
            if candidates:
                # candidates are pre-scored by DeBERTa in the caller; pick the highest score
                best = max(candidates, key=lambda x: x.get('score', 0))
                print(f"    ⚠ Falling back to best-scored candidate (score={best.get('score')})")
                return best['element']
        except Exception as e:
            print(f"    Fallback selection failed: {e}")

        print("    ✗ No element selected after parsing and fallback")
        return None


    def _ground_using_textual_choice(self, 
                                     annotation_id:str, 
                                     textual_plan: str, 
                                     step_info: Dict,
                                     top_k: int = 50):        
        print(f"    Grounding using Textual Choice for annotation '{annotation_id}'...")
        start_time = time.time()

        # get cleaned HTML value
        cleaned_html = step_info.get("cleaned_html", "")

        # Get DOM like interactive elements
        elements = extract_interactive_elements(cleaned_html)
        
        # Cross-encoder ranking: feed (plan, element) pairs through DeBERTa
        # so the model can do token-level cross-attention between the plan and
        # each candidate element (much stronger than bi-encoder cosine).
        element_reprs = [el["representation"] for el in elements]
        scores = self.deberta_loader.compute_cross_scores_batch(
            textual_plan, element_reprs
        )

        scored_elements = [
            {"score": score, "element": el}
            for score, el in zip(scores, elements)
        ]
        scored_elements.sort(key=lambda x: x["score"], reverse=True)


        # select top-k elements based on cross-encoder relevance scores
        top_k_elements = scored_elements[:top_k]

        # Free CUDA cache before Qwen VL inference to avoid OOM on small GPUs
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # ask qwen model to select best matching element from top-k
        website_screenshot = step_info.get("screenshot", None)

        selected_element = self.select_element_from_candidates(textual_plan, top_k_elements, website_screenshot, step_info["instruction"])

        # return the selected element as the grounded action
        if selected_element is None:
            print(f"    ✗ No element selected for annotation '{annotation_id}'.")
            return {
                "success": False,
                "error": "No element selected",
                "selected_element": None,
                "latency": time.time() - start_time
            }

        return {
            "success": True,
            "error": None,
            "selected_element": selected_element,
            "latency": time.time() - start_time
        }

    def _ground_using_image_annotation(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using image annotation
        print(f"    Grounding using Image Annotation for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using image annotation.
        pass

    def _invalid_method(self, annotation_id:str, textual_plan: str, step_info: Dict):
        print(f"    ✗ Invalid grounding method specified for annotation '{annotation_id}'.")
        return None

    def process(
                self,  
                annotation_id:str,
                textual_plan: str,
                step_info: Dict,
                ) -> Dict:
        """
        Process the action grounding based on the specified method.
        
        Args:            
            annotation_id: Identifier for the current annotation being processed.
            textual_plan: The textual plan generated by the action generation module for the current step.
            step_info: Additional information about the current step (e.g., DOM snapshot, screenshots, etc.)        
        Returns:
            Grounded action details (format may vary based on method).
        """

        print(f"  ⏳ Processing action grounding for annotation '{annotation_id}'...")       
        
        result = self.grounding_function(annotation_id, textual_plan, step_info)


        # Here we would have the actual code to perform action grounding based on the specified method.
        # For now, we will just return a placeholder string.
        return result