"""
Action Grounding Module

SeeAct Action Grounding Module: responsible for grounding action plans generated by the action generation module into concrete UI actions.

Input:
- Textual Plan 
- loaded model (Qwen-2.4-VL-2B-Instruct), used when required for grounding
- action value (Image, Instruction, DOM value, etc.)
- annotation id (for logging/debugging purposes)
- Method number (1-3) 
1. Element Attributes 
2. Textual Choice 
3. Image Annotation
"""

import time
import torch
from AutoWeb.src.config import get_deberta_model_path
from AutoWeb.src.model_interface import VLModel
from AutoWeb.src.gpt_model import GPTVisionModel
from typing import Dict, List, Union

from AutoWeb.src.utils.html_to_dom import extract_interactive_elements
from AutoWeb.src.utils.img_downscaler import downscale_image_if_needed
from AutoWeb.src.utils.load_DeBERTa import DeBERTaLoader
from AutoWeb.src.logger import logger
import re
import json
import ast


class SeeActActionGrounding:
    def __init__(
            self, 
            model: Union[VLModel, GPTVisionModel],
            method: str = "2"
            ):
        self.model = model
        self.method = method

        self.switcher = {
            "1": self._ground_using_element_attributes,
            "2": self._ground_using_textual_choice,
            "3": self._ground_using_image_annotation
        }

        self.grounding_function = self.switcher.get(self.method, self._invalid_method)

        if self.grounding_function == self._invalid_method:
            logger.warning(f"⚠️ Warning: Invalid grounding method '{self.method}' specified. Defaulting to invalid method handler.")
            # Block execution if the method is invalid
            raise ValueError(f"Invalid grounding method '{self.method}' specified. Please choose a valid method (1, 2, or 3).") 
        
        # Load the DeBERTa model for groudning method "2" (Textual Choice)
        self.deberta_loader = None
        self.deberta_model = None
        if self.method == "2":
            self.load_deberta()
            logger.info(f"  ✅ DeBERTa model loaded successfully.")
        


    def load_deberta(self):        
        deberta_model_path = get_deberta_model_path()
        
        # Use pre-trained cross-encoder from sentence-transformers (recommended).
        # Falls back to legacy DeBERTa-base + random head only if explicitly disabled.
        self.deberta_loader = DeBERTaLoader(
            model_path=deberta_model_path,
            use_pretrained_crossencoder=True,           # ← pre-trained cross-encoder
            crossencoder_name="cross-encoder/ms-marco-MiniLM-L-6-v2",
        )
        self.deberta_loader.load_model()
        self.deberta_model = self.deberta_loader.model  # may be None for pre-trained path

    def _ground_using_element_attributes(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using element attributes
        logger.info(f"    Grounding using Element Attributes for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using element attributes.
        pass

    @staticmethod
    def _normalize_ws(text: str) -> str:
        return " ".join((text or "").split())

    def _compact_candidate_line(self, rank_idx: int, candidate: Dict) -> str:
        """
        Build a compact candidate representation for LLM grounding prompts.
        This prevents TPM blow-ups from massive subtree text payloads.
        """
        element = candidate.get("element", {}) if isinstance(candidate, dict) else {}
        tag = element.get("tag", "?")
        raw_text = self._normalize_ws(str(element.get("text", "")))
        if len(raw_text) > 120:
            raw_text = raw_text[:120] + "..."

        attrs = element.get("attributes", {}) if isinstance(element.get("attributes"), dict) else {}
        keep_keys = (
            "backend_node_id",
            "role",
            "name",
            "aria_label",
            "placeholder",
            "type",
            "value",
            "input_value",
        )
        compact_attrs = {}
        for key in keep_keys:
            val = attrs.get(key)
            if val is None:
                continue
            sval = self._normalize_ws(str(val))
            compact_attrs[key] = (sval[:80] + "...") if len(sval) > 80 else sval

        score = candidate.get("score", 0.0)
        return f'{rank_idx}. <{tag}> text="{raw_text}" attrs={compact_attrs} (score: {score:.4f})'

    def select_element_from_candidates(self, textual_plan: str, candidates: List[Dict], website_screenshot, user_instruction: str = ""):
        """
        Grounding Using Textual Choice - Select the best matching element from the top candidates using the Qwen model.
        """
        safe_instruction = self._normalize_ws(str(user_instruction))
        safe_plan = self._normalize_ws(str(textual_plan))
        if len(safe_instruction) > 220:
            safe_instruction = safe_instruction[:220] + "..."
        if len(safe_plan) > 200:
            safe_plan = safe_plan[:200] + "..."

        # Build compact candidate list for GPT grounding to avoid massive token payload.
        enumerated_candidates = "\n".join(
            [self._compact_candidate_line(i, c) for i, c in enumerate(candidates)]
        )

        # Compact prompt that forces a single-line 'Answer: <index|NO_MATCH>' output.
        # For API models the image is skipped (DeBERTa already ranked candidates),
        # so we omit the screenshot placeholder to avoid confusing the LLM.
        _is_api_model = isinstance(self.model, GPTVisionModel)

        if _is_api_model:
            # Text-only prompt — no image, no screenshot reference
            prompt = f"""You select the best UI element candidate for the next single action.
Return EXACTLY ONE token only:
- 0-based candidate index (e.g., 3), or
- NO_MATCH
Do not return JSON or explanations.

user instruction: {safe_instruction}
plan: {safe_plan}

Candidates (scored by relevance model, descending):
{enumerated_candidates}

Answer:
"""
        else:
            # Local Qwen model — include image placeholder
            prompt = f"""
You select the best UI element candidate for the next single action.
Return EXACTLY ONE token only:
- 0-based candidate index (e.g., 3), or
- NO_MATCH
Do not return JSON or explanations.

user instruction: {safe_instruction}
plan: {safe_plan}

Website screenshot: <|vision_start|><|image_pad|><|vision_end|>

Candidates:
{enumerated_candidates}

Answer:
"""

        # Deterministic generation: low token budget, no sampling
        # For local Qwen, downscale to limit VRAM / patch-token count.

        def _prepare_image(img):
            if img is None:
                return None
            if _is_api_model:
                return img  # full quality, no resize
            return downscale_image_if_needed(img)

        def call_model(p, max_tokens=6):
            # For API models (GPT-4o), grounding is text-only: no image.
            # DeBERTa already ranked candidates by relevance; GPT only
            # confirms the best index from compact text descriptions.
            # Skipping the image eliminates:
            #   • Supabase upload + CDN propagation wait per grounding call
            #   • CDN timeout errors ("Timeout while downloading ...")
            #   • ~85–25K image tokens per grounding call (depending on detail)
            # For local Qwen, the image is still sent (downscaled).
            if _is_api_model:
                grounding_image = None   # text-only for API models
            else:
                grounding_image = _prepare_image(website_screenshot)

            infer_kwargs = dict(
                image_or_tensor=grounding_image,
                prompt_text=p,
                max_new_tokens=max_tokens,
                do_sample=False,
                temperature=0.0,
            )
            r = self.model.infer(**infer_kwargs)
            if isinstance(r, dict):
                # IMPORTANT: do not stringify full dict on empty output.
                # It can contain unrelated numbers (latency/tokens) that break index parsing.
                return (r.get('output_text') or r.get('raw_text') or "").strip(), r
            return str(r).strip(), r

        resp_text, raw_resp = call_model(prompt, max_tokens=6)
        logger.info(f"    Model response for element selection (text): {resp_text}")

        # quick retry with stricter instruction if response is not a single token
        retry_prompt = prompt + "\n(Reply with a single token: an integer index or NO_MATCH)"
        retry_attempted = False
        if not re.search(r"\b(NO_MATCH|\d+)\b", resp_text, re.IGNORECASE):
            retry_attempted = True
            logger.warning("    ⚠ Initial response not parseable — retrying with stricter prompt")
            resp_text, raw_resp = call_model(retry_prompt, max_tokens=4)
            logger.info(f"    Retry response: {resp_text}")
        
        # Diagnostics: show top candidates (reprs) to help debugging
        try:
            preview_candidates = [self._compact_candidate_line(i, c) for i, c in enumerate(candidates[:5])]
            logger.debug(f"    Candidate count={len(candidates)}, top previews={preview_candidates}")
        except Exception:
                    pass
        # 1) Try plain integer extraction (single digit or multi-digit)
        m = re.search(r"\b(\d+)\b", resp_text)
        if m:
            try:
                idx = int(m.group(1))
                if 0 <= idx < len(candidates):
                    logger.info(f"   Selected element : {candidates[idx]['element']},  (index {idx})")
                    return candidates[idx]["element"]
                else:
                    logger.warning(f"    Parsed index {idx} out of range (0..{len(candidates)-1})")
            except Exception as e:
                logger.exception(f"    Error converting parsed index: {e}")

        json_obj = None
        jmatch = re.search(r"Selected element\s*[:\-\[]\s*(\{.*\})", resp_text, re.DOTALL | re.IGNORECASE)
        if jmatch:
            js = jmatch.group(1)
            try:
                json_obj = json.loads(js)
            except Exception:
                try:
                    json_obj = ast.literal_eval(js)
                except Exception:
                    json_obj = None

        # 3) If we received a JSON-like object as the whole response, try to parse it
        if not json_obj:
            try:
                if resp_text.startswith('{') and resp_text.endswith('}'):
                    json_obj = json.loads(resp_text)
            except Exception:
                try:
                    json_obj = ast.literal_eval(resp_text)
                except Exception:
                    json_obj = None

        # 4) If JSON object found, try to match its 'text' or attributes against candidates
        if isinstance(json_obj, dict):
            probe_text = json_obj.get('text') or ''
            # if probe_text is empty, try attributes -> join attribute values
            if not probe_text and isinstance(json_obj.get('attributes'), dict):
                probe_text = ' '.join(str(v) for v in json_obj['attributes'].values() if v)

            probe_text = probe_text.strip()
            if probe_text:
                # basic string-match scoring
                best_idx = None
                best_score = 0
                for i, c in enumerate(candidates):
                    repr_text = c['element'].get('representation', '') or ''
                    a = repr_text.lower()
                    b = probe_text.lower()
                    score = 0
                    if b in a or a in b:
                        score = max(score, 100)
                    # token overlap
                    toks_a = set(a.split())
                    toks_b = set(b.split())
                    ov = len(toks_a & toks_b)
                    score += ov
                    if score > best_score:
                        best_score = score
                        best_idx = i
                if best_idx is not None and best_score > 0:
                    logger.info(f"    Matched JSON 'text' to candidate index={best_idx} (score={best_score})")
                    return candidates[best_idx]['element']
                else:
                    logger.warning("    JSON returned by model contained text but no candidate matched confidently")
            else:
                logger.warning("    JSON returned by model is empty or has no text/attributes")

        # 5) As a robust fallback, pick the top DeBERTa/scored candidate (best similarity)
        try:
            if candidates:
                # candidates are pre-scored by DeBERTa in the caller; pick the highest score
                best = max(candidates, key=lambda x: x.get('score', 0))
                logger.warning(f"    ⚠ Falling back to best-scored candidate (score={best.get('score')})")
                return best['element']
        except Exception as e:
            logger.exception(f"    Fallback selection failed: {e}")

        logger.error("    ✗ No element selected after parsing and fallback")
        return None


    def _ground_using_textual_choice(self, 
                                     annotation_id:str, 
                                     textual_plan: str, 
                                     step_info: Dict,
                                     top_k: int = 50):        
        logger.info(f"    Grounding using Textual Choice for annotation '{annotation_id}'...")
        start_time = time.time()

        # get cleaned HTML value
        cleaned_html = step_info.get("cleaned_html", "")

        # Get DOM like interactive elements
        elements = extract_interactive_elements(cleaned_html)
        
        # Cross-encoder ranking: feed (plan, element) pairs through DeBERTa
        # so the model can do token-level cross-attention between the plan and
        # each candidate element (much stronger than bi-encoder cosine).
        element_reprs = [el["representation"] for el in elements]
        scores = self.deberta_loader.compute_cross_scores_batch(
            textual_plan, element_reprs
        )

        scored_elements = [
            {"score": score, "element": el}
            for score, el in zip(scores, elements)
        ]
        scored_elements.sort(key=lambda x: x["score"], reverse=True)


        # select top-k elements based on cross-encoder relevance scores
        # GPT grounding uses a smaller top-k to keep token load under TPM limits.
        effective_top_k = 12 if isinstance(self.model, GPTVisionModel) else top_k
        top_k_elements = scored_elements[:effective_top_k]

        # Free CUDA cache before Qwen VL inference to avoid OOM on small GPUs
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # ask qwen model to select best matching element from top-k
        website_screenshot = step_info.get("screenshot", None)

        selected_element = self.select_element_from_candidates(textual_plan, top_k_elements, website_screenshot, step_info["instruction"])

        # return the selected element as the grounded action
        if selected_element is None:
            logger.error(f"    ✗ No element selected for annotation '{annotation_id}'.")
            return {
                "success": False,
                "error": "No element selected",
                "selected_element": None,
                "latency": time.time() - start_time
            }

        return {
            "success": True,
            "error": None,
            "selected_element": selected_element,
            "latency": time.time() - start_time
        }

    def _ground_using_image_annotation(self, annotation_id:str, textual_plan: str, step_info: Dict):
        # Placeholder for grounding logic using image annotation
        logger.info(f"    Grounding using Image Annotation for annotation '{annotation_id}'...")
        # Here we would have the actual code to perform grounding using image annotation.
        pass

    def _invalid_method(self, annotation_id:str, textual_plan: str, step_info: Dict):
        logger.error(f"    ✗ Invalid grounding method specified for annotation '{annotation_id}'.")
        return None

    def process(
                self,  
                annotation_id:str,
                textual_plan: str,
                step_info: Dict,
                ) -> Dict:
        """
        Process the action grounding based on the specified method.
        
        Args:            
            annotation_id: Identifier for the current annotation being processed.
            textual_plan: The textual plan generated by the action generation module for the current step.
            step_info: Additional information about the current step (e.g., DOM snapshot, screenshots, etc.)        
        Returns:
            Grounded action details (format may vary based on method).
        """

        logger.info(f"  ⏳ Processing action grounding for annotation '{annotation_id}'...")       
        
        result = self.grounding_function(annotation_id, textual_plan, step_info)


        # Here we would have the actual code to perform action grounding based on the specified method.
        # For now, we will just return a placeholder string.
        return result
